name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Run linter (ruff)
      run: make lint
    
    - name: Run type checker (mypy)
      run: make typecheck
    
    - name: Run tests
      run: make test
    
  build-lambda:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    
    - name: Install dependencies
      run: pip install -e .
    
    - name: Build Lambda package
      run: make build_lambda_scan_ebs
    
    - name: Upload Lambda artifact
      uses: actions/upload-artifact@v4
      with:
        name: lambda-deployment-package
        path: dist/scan_ec2_unattached_ebs.zip
        retention-days: 30
  
  terraform-validate:
    runs-on: ubuntu-latest
    needs: build-lambda
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.5.0"
    
    - name: Terraform Init
      working-directory: infra/terraform
      run: terraform init -backend=false
    
    - name: Terraform Format Check
      working-directory: infra/terraform
      run: terraform fmt -check
    
    - name: Terraform Validate
      working-directory: infra/terraform
      run: terraform validate
